### ISSUE TITLE
globbing support?

### ISSUE THREAD

**Issue by lan3jur** [broccolijs/broccoli-funnel#24]
Hi,
is it possible to provide wildcards / globbing when using the files option?
For example:
var someFiles = funnel('src', {
  files: ['*.html']
});
Thanks!

**Comment by marcenuc** [comment]
@lan3jur, the following works fine:

    var someFiles = funnel('src', {
      include: ['**/*.html']
    });

**Comment by marcenuc** [comment]
@lan3jur, see also #9

**Comment by lan3jur** [comment]
Sorry for late reply.. Indeed, it was my mistake, I made a terrible typo and didn't even notice it for days :(
Sorry for the trouble..

**Comment by stefanpenner** [comment]
question appears to be answered, if I am mistaken leave a comment explaining why and we can reopen.
