### ISSUE TITLE
Consider a rename of the plugin/project to more accurately reflect what it does.

### ISSUE THREAD

**Issue by dustyburwell** [broccolijs/broccoli-funnel#3]
Reading through the documentation, this plugin doesn't seem to function as a funnel at all. It may make sense to rename to more accurately reflect it's purpose. Some more accurate names might be sieve, strainer, or colander. Personally, I prefer colander, if only for the visual of broccoli being rinsed and drained. (how is there no animated gif for this?) Though, I'm not sure how playful the broccoli community is with their naming.

![broccoli-colander](http://comps.canstockphoto.com/can-stock-photo_csp16211482.jpg)

Obviously, renaming a project has some potentially negative side-effects as the user base adjusts to the change. However, supporting both packages and APIs for a short deprecation period shouldn't be too much overhead.

**Comment by joliss** [comment]
The naming is tricky, but I guess it's too late at this point to rename it; it's just not worth the breakage.

We *can* change the recommend function name in the README if we wanted to (`var from = require('broccoli-funnel');`). I don't really have an opinion on that.

**Comment by stefanpenner** [comment]
I believe a name change at this point will not provide much value. I suspect improving the description may help, a PR or issue with some suggestions will be evaluated.
