### ISSUE TITLE
Regression in release 0.2.6

### ISSUE THREAD

**Issue by krisselden** [broccolijs/broccoli-funnel#35]
Broccoli funnel filters out files in subdirs that would have matched the include filters in earlier versions.

```
    var tree = new Funnel(iconsPath, {
      include: [ '*.scss' ],
    });
```

```
  readdirSync(iconsPath); // returns ['icons.scss', ...]
```

**Comment by rwjblue** [comment]
A glob of `*.scss` generally should not include subdirectories (it should only match `.scss` files in the root of the tree), nested subdirectories would be matched by `**/*.scss`.

If it previously did match I guess it is a breaking change, but making `*.scss` match all subdir contents is somewhat weird.

**Comment by stefanpenner** [comment]
the example and the description appear different. the example does not include sub-dirs for the matcher.

**Comment by rwjblue** [comment]
Can you give us an example contents of the input tree, and which specific files you expected to be matched by `include: [ '*.scss' ]`?

**Comment by stefanpenner** [comment]
Anyways, I believe I have solved the issue. Or maybe just one that manifests in a similar way

**Comment by stefanpenner** [comment]
doing a NOM, should fix. Be sure your local copy of walk-sync-matcher is 0.2.2 or greater.
