### ISSUE TITLE
Please change examples to `funnel`, not `new Funnel`

### ISSUE THREAD

**Issue by alanhogan** [broccolijs/broccoli-funnel#41]
In short, documenting `Funnel` as a `class` is leading some devs to treat Funnel differently than other Broccoli and even Node modules. Look how Funnel sticks out like a sore thumb:

```js
var mergeTrees = require('broccoli-merge-trees'),
    Funnel = require('broccoli-funnel'),
    concat = require('broccoli-concat'),
    path = require('path'),
    find = require('lodash/collection/find'),
    fs = require('fs');
```

If I made a brief PR to change example usages in README, would you accept it?

**Comment by rwjblue** [comment]
New should be used with all of them. We are making this te default for all official plugins (and the vast majority of plugins work fine when used with new already).

**Comment by alanhogan** [comment]
Fine.
