### ISSUE TITLE
Recursively walk directory

### ISSUE THREAD

**Issue by billybonks** [broccolijs/broccoli-funnel#63]
```shell
.
├── Brocfile.js
└── src/
    ├── css/
    │   ├── reset.css
    │   └── todos.css
    │   ├── morecss/
          │   ├── reset.css
          │   └── todos.css

```

new Funnel('src/css') does not walk morecss.

**Comment by stefanpenner** [comment]
> new Funnel('src/css') does not walk morecss.

https://github.com/broccolijs/broccoli-funnel/blob/master/tests/index.js#L388-L409 seems to not agree with this issue, can you provide a reproduction demonstrating your issue?

**Comment by stefanpenner** [comment]
would love to address this issue, but without further information (and tests that seem to indicate this isn't the case) I am not sure what we can do. 

Will gladly reopen if further more actionable information can be provided.

**Comment by Asherlc** [comment]
@stefanpenner I think I might be having this same issue -- could the difference be that in the referenced test, you supply a specific `files` option?  Is it expected that just `Funnel('src/css')` (sans `files`), would include `morecss`?

**Comment by stefanpenner** [comment]
@Asherlc mind opening a second issue, \w clear steps to reproduce. I will gladly debug :)

**Comment by Asherlc** [comment]
Ah, never mind, I think I was using an out of date version.

--
Asher Cohen
asherlc@asherlc.com


On Fri, Aug 5, 2016, at 12:10 PM, Stefan Penner wrote:
> @Asherlc[1] mind opening a second issue, \w clear steps to reproduce.
> I will gladly debug :)
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>


Links:

  1. https://github.com/Asherlc
  2. https://github.com/broccolijs/broccoli-funnel/issues/63#issuecomment-237937611

**Comment by stefanpenner** [comment]
@Asherlc ah, awesome!
