### ISSUE TITLE
Incompatible with heimdalljs 0.1.3?

### ISSUE THREAD

**Issue by drewcovi** [broccolijs/broccoli-funnel#71]
getting a message that this is no longer compatible...

Version "0.1.2" not compatible with "^0.1.3"

Does package.json need updating?

**Comment by hjdivad** [comment]
@drewcovi do you still get this error if you `rm -rf ./node_modules && npm i`?  I would expect very few users to end up with `0.1.2`.

Having said that it's fine for us to upgrade `package.json` to depend on `^0.1.3`

**Comment by drewcovi** [comment]
I've been clearing cache and removing ember-moment (ember-cli-moment-shim) from my node_modules, and I believe I do have 0.1.3 when I look at what's installed. yet for some reason it still must think I have 0.1.2. not entirely sure unfortunately.

**Comment by drewcovi** [comment]
im not sure how process._heimdall.version is returned and why it would be out of sync with the latest version that lives in node_modules.

**Comment by hjdivad** [comment]
@drewcovi you can do `npm ls heimdalljs` to see where you're getting your version `0.1.2` from.

**Comment by drewcovi** [comment]
```
├─┬ ember-bootstrap@0.8.0
│ ├─┬ broccoli-funnel@1.0.3
│ │ └─┬ fs-tree-diff@0.5.1
│ │   └─┬ heimdalljs-logger@0.1.6
│ │     └── heimdalljs@0.1.2 
│ └─┬ broccoli-merge-trees@1.1.2
│   └─┬ fs-tree-diff@0.5.1
│     └─┬ heimdalljs-logger@0.1.6
│       └── heimdalljs@0.1.2 
├─┬ ember-cli@2.7.0
│ ├─┬ broccoli-babel-transpiler@5.5.0
│ │ └─┬ broccoli-persistent-filter@1.2.6
│ │   └─┬ fs-tree-diff@0.5.1
│ │     └─┬ heimdalljs-logger@0.1.6
│ │       └── heimdalljs@0.1.2 
│ ├─┬ broccoli-funnel@1.0.3
│ │ └─┬ fs-tree-diff@0.5.1
│ │   └─┬ heimdalljs-logger@0.1.6
│ │     └── heimdalljs@0.1.2 
│ ├─┬ broccoli-merge-trees@1.1.2
│ │ └─┬ fs-tree-diff@0.5.1
│ │   └─┬ heimdalljs-logger@0.1.6
│ │     └── heimdalljs@0.1.2 
│ ├─┬ ember-cli-preprocess-registry@2.0.0
│ │ └─┬ broccoli-clean-css@1.1.0
│ │   └─┬ broccoli-persistent-filter@1.2.6
│ │     └─┬ fs-tree-diff@0.5.1
│ │       └─┬ heimdalljs-logger@0.1.6
│ │         └── heimdalljs@0.1.2 
│ └─┬ tree-sync@1.1.2
│   └─┬ fs-tree-diff@0.5.1
│     └─┬ heimdalljs-logger@0.1.6
│       └── heimdalljs@0.1.2 
├─┬ ember-cli-babel@5.1.7
│ ├─┬ broccoli-babel-transpiler@5.5.0
│ │ ├─┬ broccoli-merge-trees@1.1.2
│ │ │ └─┬ fs-tree-diff@0.5.1
│ │ │   └─┬ heimdalljs-logger@0.1.6
│ │ │     └── heimdalljs@0.1.2 
│ │ └─┬ broccoli-persistent-filter@1.2.6
│ │   └─┬ fs-tree-diff@0.5.1
│ │     └─┬ heimdalljs-logger@0.1.6
│ │       └── heimdalljs@0.1.2 
│ └─┬ broccoli-funnel@1.0.3
│   └─┬ fs-tree-diff@0.5.1
│     └─┬ heimdalljs-logger@0.1.6
│       └── heimdalljs@0.1.2 
├─┬ ember-cli-htmlbars@1.0.10
│ └─┬ broccoli-persistent-filter@1.2.6
│   └─┬ fs-tree-diff@0.5.1
│     └─┬ heimdalljs-logger@0.1.6
│       └── heimdalljs@0.1.2 
├─┬ ember-cli-jshint@1.0.4
│ └─┬ broccoli-jshint@1.2.0
│   └─┬ broccoli-persistent-filter@1.2.6
│     └─┬ fs-tree-diff@0.5.1
│       └─┬ heimdalljs-logger@0.1.6
│         └── heimdalljs@0.1.2 
├─┬ ember-cli-mirage@0.2.1
│ ├─┬ broccoli-funnel@1.0.3
│ │ └─┬ fs-tree-diff@0.5.1
│ │   └─┬ heimdalljs-logger@0.1.6
│ │     └── heimdalljs@0.1.2 
│ └─┬ broccoli-merge-trees@1.1.2
│   └─┬ fs-tree-diff@0.5.1
│     └─┬ heimdalljs-logger@0.1.6
│       └── heimdalljs@0.1.2 
├─┬ ember-cli-qunit@2.1.0
│ ├─┬ broccoli-babel-transpiler@5.5.0
│ │ └─┬ broccoli-persistent-filter@1.2.6
│ │   └─┬ fs-tree-diff@0.5.1
│ │     └─┬ heimdalljs-logger@0.1.6
│ │       └── heimdalljs@0.1.2 
│ ├─┬ broccoli-funnel@1.0.3
│ │ └─┬ fs-tree-diff@0.5.1
│ │   └─┬ heimdalljs-logger@0.1.6
│ │     └── heimdalljs@0.1.2 
│ └─┬ broccoli-merge-trees@1.1.2
│   └─┬ fs-tree-diff@0.5.1
│     └─┬ heimdalljs-logger@0.1.6
│       └── heimdalljs@0.1.2 
├─┬ ember-data@2.7.0
│ ├─┬ broccoli-babel-transpiler@5.5.0
│ │ ├─┬ broccoli-funnel@1.0.3
│ │ │ └─┬ fs-tree-diff@0.5.1
│ │ │   └─┬ heimdalljs-logger@0.1.6
│ │ │     └── heimdalljs@0.1.2 
│ │ └─┬ broccoli-persistent-filter@1.2.6
│ │   └─┬ fs-tree-diff@0.5.1
│ │     └─┬ heimdalljs-logger@0.1.6
│ │       └── heimdalljs@0.1.2 
│ └─┬ broccoli-merge-trees@1.1.2
│   └─┬ fs-tree-diff@0.5.1
│     └─┬ heimdalljs-logger@0.1.6
│       └── heimdalljs@0.1.2 
├── UNMET PEER DEPENDENCY ember-inflector@^1.9.4
└─┬ ember-welcome-page@1.0.3
  ├─┬ broccoli-funnel@1.0.3
  │ └─┬ fs-tree-diff@0.5.1
  │   └─┬ heimdalljs-logger@0.1.6
  │     └── heimdalljs@0.1.2 
  └─┬ broccoli-merge-trees@1.1.2
    └─┬ fs-tree-diff@0.5.1
      └─┬ heimdalljs-logger@0.1.6
        └── heimdalljs@0.1.2 
```

**Comment by hjdivad** [comment]
It's read from the first heimdalljs instance that installs itself as the global.  see https://github.com/heimdalljs/heimdalljs-lib/blob/master/index.js

**Comment by drewcovi** [comment]
so does this mean ill have to blow away the entire node modules directory for the project and reinstall everything?

**Comment by hjdivad** [comment]
@drewcovi huh, if you blow away `node_modules` i would expect `npm i` to get you 0.1.3.

to confirm `npm info --json heimdalljs` shows you version 0.1.3 right?

**Comment by drewcovi** [comment]
yessir... seems odd this is the first time ive run into this with addons...

**Comment by drewcovi** [comment]
can do of course, probably unique as this is used quite extensively.

**Comment by hjdivad** [comment]
@drewcovi it's due to the release of broccoli-funnel earlier today; but the window of time when funnel 1.0.4 is released and heimdalljs 0.1.2 is released and heimdalljs 0.1.3 is not released is extremely small, which is why i'm surprised you are getting 0.1.2 versions of heimdalljs

**Comment by hjdivad** [comment]
@drewcovi blowing away `node_modules` is easier, but strictly speaking i would expect you just need to remove the `heimdalljs` instances eg

```sh
# remove these
find node_modules -type d -name 'heimdalljs'
```

**Comment by drewcovi** [comment]
hmmmm seems better to just take the nuke approach... guess i just got lucky :) so long as its just me no problem. ill nuke it.

**Comment by hjdivad** [comment]
@drewcovi if you nuke `node_modules` and then `npm i` and still have `0.1.2` versions of heimdalljs please let me know!

**Comment by hjdivad** [comment]
also thanks for your patience ^_^

**Comment by drewcovi** [comment]
of course! thanks for your contributions 👍

**Comment by hjdivad** [comment]
i believe we've resolved this.

Please re-open if there is still an issue.
