### ISSUE TITLE
This project appears to introduce 581 files via itself and its deps 

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli-funnel#72]
deps we may want to investigate
----

 - [ ] array-equal       7
 - [ ] blank-object       8
 - [ ] broccoli-plugin     239 https://github.com/broccolijs/broccoli-plugin/issues/13
 - [ ] debug      20
 - [ ] fast-ordered-set      21
 - [ ] fs-tree-diff      87
 - [ ] minimatch      27
 - [ ] mkdirp      45 https://github.com/substack/node-mkdirp/issues/108
 - [ ] path-posix       8
 - [ ] rimraf      56
 - [ ] symlink-or-copy      11
 - [ ] walk-sync      20

**Comment by rwjblue** [comment]
Hmm, those numbers don't seem to add up to 4864.  What am I missing?

**Comment by stefanpenner** [comment]
copy pasta oops

**Comment by locks** [comment]
[minimatch validated](https://github.com/isaacs/minimatch/blob/master/package.json#L26-L28). [Sent PR to brace-expansion dependency](https://github.com/juliangruber/brace-expansion/pull/29)

**Comment by stefanpenner** [comment]
https://github.com/broccolijs/broccoli-plugin/issues/13 has been addressed (the biggest offender)
